# Based on
# - https://github.com/srggrs/assign-one-project-github-action

name: add-issue-to-project-t-g2-python.yaml

on:
  issues:
    types:
      - reopened
      - opened

env:
  GITHUB_TOKEN: ${{ secrets.SENZING_GITHUB_ACCESS_TOKEN }}

jobs:
  add-issue-to-project:
    name: Add issue to Senzing G2 Python project
    runs-on: ubuntu-latest
    steps:
      - name: Assign issue to project
        uses: Senzing/github-action-add-issue-to-project@main
        with:
          project: "https://github.com/orgs/Senzing/projects/8"
          column_name: "Backlog"
